# Generated by Django 3.2.14 on 2022-07-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studnet_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studnet',
            name='col',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studnet',
            name='room',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studnet',
            name='row',
            field=models.IntegerField(null=True),
        ),
    ]
