# Generated by Django 3.2.14 on 2022-07-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_studnet_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studnet',
            new_name='Student',
        ),
    ]
