# Generated by Django 3.2.14 on 2022-07-14 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_studnet_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 13, 37, 40, 543317)),
        ),
    ]
