# Generated by Django 3.2.14 on 2022-07-14 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_student_last_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_name',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='login',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='room',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='second_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 21, 27, 29, 634955)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
