# Generated by Django 3.2.14 on 2022-07-14 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220714_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AlterField(
            model_name='student',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 21, 35, 57, 716797)),
        ),
    ]
