# Generated by Django 3.2.14 on 2022-07-19 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220718_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='eng_group',
            field=models.CharField(default='eng1', max_length=4),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 23, 44, 42, 1508)),
        ),
        migrations.AddField(
            model_name='teacher',
            name='master',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 23, 44, 42, 1508)),
        ),
    ]
