# Generated by Django 3.2.14 on 2022-07-19 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220719_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lang_group',
            field=models.CharField(default='nie1', max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='eng_group',
            field=models.CharField(default='ang1', max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 23, 48, 22, 903420)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 23, 48, 22, 903420)),
        ),
    ]
