# Generated by Django 3.2.14 on 2022-07-19 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220719_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='1A', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 23, 48, 50, 821843)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 23, 48, 50, 821843)),
        ),
    ]
